global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'recommandation-service'
    metrics_path: '/recommandation-service/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8087']
        labels:
          service: 'recommandation-service'