services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning" ]
    restart: unless-stopped
    networks:
      - shared_network_local
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  redisinsight:
    image: redis/redisinsight:2.70
    container_name: redisinsight
    ports:
      - "5540:5540"
    environment:
      - REDISINSIGHT_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - shared_network_local
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--spider", "http://localhost:5540" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  redis-data:
    name: redis-data

networks:
  shared_network_local:
    external: true
    name: shared_network_local
