apiVersion: 1

datasources:
  - name: ClickHouse-Local
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true

    jsonData:
      host: host.docker.internal
      port: 8123
      protocol: http
      defaultDatabase: events_db
      username: default

    secureJsonData:
      password: ""
