services:
  maildev:
    image: maildev/maildev:latest
    container_name: maildev
    restart: unless-stopped
    ports:
      - "1080:1080"
      - "1025:1025"
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:1080/ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - shared_network_local

networks:
  shared_network_local:
    external: true
