services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    ports:
      - "9443:9443"
      - "8000:8000"
    networks:
      - shared_network_local

volumes:
  portainer_data:

networks:
  shared_network_local:
    external: true
    name: shared_network_local
