services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    # start-dev is recommended for development to run without HTTPS/TLS setup
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - shared_network_local
    restart: unless-stopped

networks:
  shared_network_local:
    external: true
